CREATE OR REPLACE DATABASE probas;
USE probas;

CREATE TABLE libros (
    id INT(11) NOT NULL AUTO_INCREMENT ,
    titulo VARCHAR(100)NOT NULL,
    autor VARCHAR(100)NOT NULL,
    sinopsis VARCHAR(400)NOT NULL,
    isbn VARCHAR(20)NOT NULL,
PRIMARY KEY(id)
)